[package]
name = "libunftp"
version = "0.5.1"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Maarten Dirkse <mdirkse@bol.com>",
    "Steven Meunier <smeunier@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
    "Werner Hofstra <wernerhofstra@gmail.com>",
   ]
description = "Safe, fast and extensible FTP server library for Rust."
documentation = "https://docs.rs/libunftp/"
repository = "https://github.com/bolcom/libunftp"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ftp"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
async-trait = "0.1.22"
bytes = "0.5.4"
chrono = {version = "0.4.10", features = ["serde"]}
failure = "0.1"
failure_derive = "0.1"
futures = {version = "0.3", features = ["compat"]}
futures-util = "0.3.1"
http = { version = "0.2", optional = true }
hyper = { version = "0.13.2", optional = true, features = ["stream"]}
itertools = "0.8.2"
lazy_static = "1.3.0"
log = "0.4"
pam-auth = { version = "0.5.0", optional = true }
path_abs = "0.4"
prometheus = "0.7"
rand = "0.6"
regex = "1"
rustls = "0.16.0"
serde = { version = "1.0.104", optional = true, features = ["derive"]}
serde_json = { version = "1.0.46", optional = true }
tokio = {version = "0.2.9", features = ["fs", "io-util", "macros"]}
tokio-io = "0.1"
tokio-util = "0.2"
url = { version = "1.7.2", optional = true }
uuid = { version = "0.7", features = ["v4"] }

hyper-rustls = {version = "0.19.1", optional = true}
yup-oauth2 = {version = "4.0.0", optional = true}
mime = {version = "0.3.13", optional = true}

[dev-dependencies]
tempfile = "3"
ftp = "3"
pretty_env_logger = "0.2"
pretty_assertions = "0.5"
rand = "0.6"

[features]
pam = ["pam-auth"]
oauth2 = ["yup-oauth2", "hyper-rustls"]
cloud_storage = ["oauth2", "mime", "url", "hyper", "serde", "serde_json"]
rest = ["hyper", "url", "http", "serde", "serde_json"]

[[example]]
name = "pam"
required-features = ["pam"]

[[example]]
name = "gcs"
required-features = ["cloud_storage"]

[[example]]
name = "rest"
required-features = ["rest"]
